### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_cfg.cli' When Running CLI

### ISSUE THREAD

**Issue by gfesatidis** [epfl-dlab/transformers-CFG#89] opened 2024-09-03 10:32 UTC
**Description**:  
After installing the `transformers-cfg` package using `pip install transformers-cfg`, I'm encountering an error when attempting to run the CLI tool (`transformers-cfg-cli`). This behavior does not occur when the package is installed directly via the `setup.py` script. The error traceback is as follows:

```bash
Traceback (most recent call last):
  File "/home/gfesatidis/.miniconda3/envs/transformers-cfg/bin/transformers-cfg-cli", line 5, in <module>
    from transformers_cfg.cli.cli_main import main
ModuleNotFoundError: No module named 'transformers_cfg.cli'
```

**Steps to Reproduce**:

1. Install the package: `pip install transformers-cfg`

2. Attempt to run the CLI tool: `transformers-cfg-cli -h`

**Expected Behavior**:
The CLI tool should execute without errors, displaying the help message or performing the intended function.

**Actual Behavior**:
The CLI tool fails to run, raising a ModuleNotFoundError because the cli module is not found in the package.

**Additional Information**:
Upon inspecting the installed package directory (site-packages/transformers_cfg/), I noticed that the cli directory is missing. This seems to be the cause of the error.

![Screenshot 2024-09-02 222830](https://github.com/user-attachments/assets/9964da57-886e-4671-ad6b-40666645da85)

**Environment**:
Python version: 3.11.9
Environment: Conda
OS: WSL Ubuntu 24.04.1 LTS

**Comment by Saibo-creator** [comment] 2024-09-08 03:47
The problem was caused by a missing __init__.py file, which led to the cli module not being included in the distribution package. This issue has been resolved in the latest release and in commit #90 

Thank you for raising this issue! :)

**Closed by Saibo-creator** 2024-09-08 03:47 UTC
